/*{
  "login": "Catherine-23-Codes",
  "id": 183720444,
  "node_id": "U_kgDOCvNZ_A",
  "avatar_url": "https://avatars.githubusercontent.com/u/183720444?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/Catherine-23-Codes",
  "html_url": "https://github.com/Catherine-23-Codes",
  "followers_url": "https://api.github.com/users/Catherine-23-Codes/followers",
  "following_url": "https://api.github.com/users/Catherine-23-Codes/following{/other_user}",
  "gists_url": "https://api.github.com/users/Catherine-23-Codes/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/Catherine-23-Codes/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/Catherine-23-Codes/subscriptions",
  "organizations_url": "https://api.github.com/users/Catherine-23-Codes/orgs",
  "repos_url": "https://api.github.com/users/Catherine-23-Codes/repos",
  "events_url": "https://api.github.com/users/Catherine-23-Codes/events{/privacy}",
  "received_events_url": "https://api.github.com/users/Catherine-23-Codes/received_events",
  "type": "User",
  "user_view_type": "public",
  "site_admin": false,
  "name": "Cat-on-Git",
  "company": null,
  "blog": "",
  "location": "India",
  "email": null,
  "hireable": null,
  "bio": "I'm a 3rd yr CSE  student! \r\nAspiring to create a brand value that's uniquley mine ! ",
  "twitter_username": null,
  "public_repos": 30,
  "public_gists": 0,
  "followers": 17,
  "following": 16,
  "created_at": "2024-10-03T12:08:16Z",
  "updated_at": "2026-01-22T17:07:31Z"
}
*/
